export default {
  LIST_FAILURE: 'groups/LIST_FAILURE',
  LIST_REQUEST: 'groups/LIST_REQUEST',
  LIST_SUCCESS: 'groups/LIST_SUCCESS',
  LIST_PRIVATES_FAILURE: 'groups/LIST_PRIVATES_FAILURE',
  LIST_PRIVATES_REQUEST: 'groups/LIST_PRIVATES_REQUEST',
  LIST_PRIVATES_SUCCESS: 'groups/LIST_PRIVATES_SUCCESS'
}
