export default {
  AUTH_FAILURE: 'user/AUTH_FAILURE',
  AUTH_REQUEST: 'user/AUTH_REQUEST',
  AUTH_SUCCESS: 'user/AUTH_SUCCESS',
  AUTH_TOKEN_FAILURE: 'user/AUTH_TOKEN_FAILURE',
  AUTH_TOKEN_REQUEST: 'user/AUTH_TOKEN_REQUEST',
  AUTH_TOKEN_SUCCESS: 'user/AUTH_TOKEN_SUCCESS',
  LOGOUT: 'user/LOGOUT',
  REGISTER_USER_FAILURE: 'user/REGISTER_USER_FAILURE',
  REGISTER_USER_REQUEST: 'user/REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'user/REGISTER_USER_SUCCESS',
  VERIFY_USERNAME_FAILURE: 'user/VERIFY_USERNAME_FAILURE',
  VERIFY_USERNAME_REQUEST: 'user/VERIFY_USERNAME_REQUEST',
  VERIFY_USERNAME_SUCCESS: 'user/VERIFY_USERNAME_SUCCESS'
}
